### ISSUE TITLE
Clear varnish cache is called multiple times

### ISSUE THREAD

**Issue by lochmueller** [opsone-ch/typo3-varnish#42]
Hey guys,

if I copy a page incl. 50 CEs to another page, the varnish cache is triggerd multiple times (for each CE?!). There should some kind of "array_unique" in the command logic to avoid useless calls to the varnish.

Regards,
Tim

**Comment by andristeiner** [comment]
Hi Tim

The cache clearing is called whenever the corresponding hook is triggered by the TYPO3 core. I guess we could implement some kind of queue, however this seems a bit over the top to me. I'd rather leave it like this and let the TYPO3 core decide when its suitable to issue those cache clearing commands.

If you have more insights into the TYPO3 cache internals and a better idea, please let me know.

Cheers,
Andri

**Comment by lochmueller** [comment]
Hey Andri,

I think the problem is the DataHandler. The DataHandler do not checked if it is called hundert times and so, the DataHandler just call the hooks.
Do you know, that "$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_tcemain.php']['clearCachePostProc']" is used in two locations in the datahandler. In "prepareCacheFlush" and in "clear_cacheCmd". I think "prepareCacheFlush" is the wrong location and the varnish handle this call also. Even if the core "fix" the handling of the clear-cache process, I think clear_cacheCmd ist the only function the EXT:varnish should hook into ?!
https://github.com/snowflakeOps/typo3-varnish/blob/master/Classes/Hooks/DataHandler.php#L59 So ignore the call, if there is no "cacheCmd". I will check this in detail shortly...

Regards,
Tim

**Comment by andristeiner** [comment]
Hi Tim,

I did some more research and can confirm that the cache is cleared for each content element of a page copied. However, every one of those calls to the hook comes with `cacheCmd` set to the target page id, so i cannot just ignore those calls as far as i see.

I'd like to keep the whole code base as clean and near to the core as possible, i don't think its feasible to add some kind of queueing to the extension as this will complicate things to much in my opinion. Also, i don't see any other way to hook into `clear_cacheCmd` only, as `clearCachePostProc` is used in both `clear_cacheCmd` and `prepareCacheFlush`.

I'll leave this issue open for now. Please let me know if you're able to come up with a better answer in the meantime.

Cheers,
Andri

**Comment by andristeiner** [comment]
Hi Tim,

Any update from your side here? There will be a new version with TYPO3 9 compatibility soon, which will be a good opportunity to integrate other changes as well.

Thanks,
Andri

**Comment by lochmueller** [comment]
Hey @andristeiner 
There is already a Cache Tags integration for staticfilecache (not fully testet in production). By using the Cache-Tags I can clear the cache very efficient without a separat Varnish extension. In another project I fixed the hook for the Varnish cache in this extension. There are complex DataHandler operations in the Backend that call the curl_multi_exec 500.000 times (but with only 7 different call configurations). So the varnish extension trigger more requests than needed.... :(

Regards,
Tim

**Comment by stucki** [comment]
@lochmueller Can you show me the changes you did? Thanks in advance!

**Comment by lochmueller** [comment]
Hey @stucki 
for the varnish extension?
https://github.com/snowflakeOps/typo3-varnish/blob/master/Classes/Hooks/DataHandler.php#L59
This hook should only respect the cacheCmd (if empty: skip). So the Hook should not trigger VarnishController multiple times. If there is have load on the DataHandler the Hook is called multiple times for each operation (the hook is used on two places in the core, but the first is the preparation and the second is the clearCacheCmd).

Or in Staticfilecache?
There is this Tag-Service: https://github.com/lochmueller/staticfilecache/blob/master/Classes/Service/TagService.php that send the cache tags of the TSFE (incl. custom Tags) via htaccess to the varnish: https://github.com/lochmueller/staticfilecache/blob/master/Resources/Private/Templates/Htaccess.html#L30 (based on https://foshttpcache.readthedocs.io/en/stable/response-tagging.html#tags )

Did this information help? Do you need more information?
Do you mean this information? ;)

Regards,
Tim

**Comment by andristeiner** [comment]
Further proceedings in https://gitlab.com/opsone_ch/typo3/varnish/issues/1
