### ISSUE TITLE
specifing url on header not only pid with speaking url

### ISSUE THREAD

**Issue by mistre85** [opsone-ch/typo3-varnish#49]
Hi

On typo3 7.6.32 with Varnish 2.1.2 extension, when an editor disable a page, the page goes in 404 error and varnish register 404 on that URL.

if the user enable this page again, varnish are unable to remove from cache the 404 error, because there is no PID to relate the BAN, i supposed.

i want to propose a solution (beta) for this version, specifying other params in the header, the speaking url.

it's sensed solution or there is some analysis mistake?

Thanks

**this in varnish controller**
$command = array(
            $cacheCmd > 0 ? 'Varnish-Ban-TYPO3-Pid: ' . $cacheCmd : 'Varnish-Ban-All: 1',
            'Varnish-Ban-TYPO3-Sitename: ' . VarnishGeneralUtility::getSitename(),
            'Varnish-Ban-Typo3-url: ' . VarnishGeneralUtility::getPageUrl($cacheCmd)
        );

**this in VarnishGeneralUtility**

    public static function getPageUrl($cacheCmd)
    {

        $objectManager = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('TYPO3\\CMS\\Extbase\\Object\\ObjectManager');

        $urlCacheRepo = $objectManager->get(UrlCacheEntryRepository::class);

        $pages = $urlCacheRepo->findByPageId($cacheCmd);

        foreach ($pages as $page) {
            //todo: per il momento gli diamo la first ma dovremmo valutare la possibilità di cancellarle tutte,
            // dato che c'è la pagina in lingua
            return $page->getSpeakingUrl();
        }

        return "";

    }

**Comment by andristeiner** [comment]
Hi there,

Thank you for this report. Assuming you used the default configuration, 404 are cached according its page settings in TYPO3. If you have set like 1 day expire day on your 404 page, Varnish will cache it for one day.

We end up with the very same problem you describe if someone accesses page /xy which does not exist at this moment, but maybe does a few minutes later. A fix of the kind you proposed seems the only possible one for this particular problem, however this extension was created years ago exactly to get rid of URLs within the Varnish cache and im hesitant to give this up to solve this kind of edge case.

At the moment, i don't have any idea how to solve it beside of clearing the (Varnish) cache manually in the backend, which seems like a good tradeoff against the many advantages we gain by not having to deal with page urls within Varnish. Also, we're in the middle of the transition from RealURL to the core internal speaking urls, so there will be a whole other story in the future.

As said already, i don't see a technically sound and future proof solution for this at the moment. Maybe there is one, but it has to work without telling Varnish about all urls somehow.

**Comment by andristeiner** [comment]
As i did not heard anything, i will go on and close this issue. Feel free to open a new one or contact me if you still have any questions.
