### ISSUE TITLE
[Question] Does this Extension support TYPO3 v10?

### ISSUE THREAD

**Issue by MartinH0** [opsone-ch/typo3-varnish#50]
Does this extension support TYPO3 v10 and will I be able to connect Netlify with it?
I'm planning to move to Varnish just for having the possibillity to set up Webprojects statically with a CDN Service which allows me to rebuild my cache.

Also another question:
Do I have to call all pages after purging the Cache or does this have a Build-In function like "generate Cache"?

**Comment by andristeiner** [comment]
* TYPO3 10 support is not yet implemented but i'm planning to do so soon
* i don't know what part of TYPO3/Varnish you want to connect to Netlify and why Varnish will be required, but as all components speak HTTP it should work fine
* there is no built in cache warming function

**Comment by andristeiner** [comment]
Hi @MartinH0

A first version comatible with TYPO3 10 is available within the [593-typo3v10](https://github.com/opsone-ch/typo3-varnish/tree/593-typo3v10) branch. I will test and finalize those modifications over the next days (weeks?) and release a new version as soon as everything is in order an working with both 9 and 10 versions.

I appreciate if you have can test this branch by yourself in the meantime.

**Comment by andristeiner** [comment]
Merged in https://gitlab.com/opsone_ch/typo3/varnish/-/merge_requests/1. Will be released with the next version 4.0.0 soon.
