### ISSUE TITLE
Support for datasets with start/stop date

### ISSUE THREAD

**Issue by papillon6** [opsone-ch/typo3-varnish#51]
Does your extension support content with a specific start/stop date? Let's say we use a plugin on page A which renders datasets from a sysfolder B. Datasets in sysfolder B can have a start date X in the future. Does the varnish extension send a BAN command to the varnish instance on start date X?

We are struggling with this issue right now, but are unsure what exactly is causing trouble... Our guess is that varnish cache is not cleared in this case, because TYPO3 does not trigger a page cache clear command!?

**Comment by andristeiner** [comment]
Hi! The extensions is not involved directly, but the appropriate expires header are set by the core depending on your selected stop date. After this time will be reached, Varnish will throw away the cached content and a new lookup will be made to the backend where the new content is displayed.

As a first step to debug, lets check the Expires header on such a page sent by TYPO3.

**Comment by papillon6** [comment]
TYPO3 does not send an expires header at all. 
Cache / varnish related headers are:

```
Cache-Control: private, no-store
TYPO3-Pid: XXX
TYPO3-Sitename: XXX
```

Without the apropriate cache headers, it cannot work as expected ;-) Thanks for pointing me into the right direction. I will have a deeper look into TS or htaccess ...

**Comment by andristeiner** [comment]
As i did not heard anything, i will go on and close this issue. Feel free to open a new one or contact me if you still have any questions.
