### ISSUE TITLE
Error-Message when calling Command / Scheduler

### ISSUE THREAD

**Issue by markusmuellerw** [opsone-ch/typo3-varnish#54]
In Context of Scheduler / Command (CLI) there is no normalizedParams-Attribute in the Request-Object. This triggers an error while parsing typoscript:

`TYPO3 [ERROR] request="..." component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Unable to call method "isBehindReverseProxy" of non-object "request.getNormalizedParams()"`

So the Typoscript-Condition in Configuration/TypoScript/setup.typoscript should first check the existence of this attribute:

`[request.getNormalizedParams() && request.getNormalizedParams().isBehindReverseProxy()]`
 instead of
`[request.getNormalizedParams().isBehindReverseProxy()]`

Best Regards,
Markus

**Comment by andristeiner** [comment]
Thanks :bow: Moved to https://gitlab.com/opsone_ch/typo3/varnish/-/issues/15.
